module.exports = [
  
    {
      "city": "Nairobi", 
      "latitude": "-1.2864", 
      "longitude": "36.8172", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Nairobi City", 
      "capital": "primary", 
      "population": "5545000", 
      "population_proper": "5545000"
    }, 
    {
      "city": "Meru", 
      "latitude": "0.0500", 
      "longitude": "37.6500", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Meru", 
      "capital": "admin", 
      "population": "1833000", 
      "population_proper": "1833000"
    }, 
    {
      "city": "Mombasa", 
      "latitude": "-4.0500", 
      "longitude": "39.6667", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Mombasa", 
      "capital": "admin", 
      "population": "1200000", 
      "population_proper": "1200000"
    }, 
    {
      "city": "Kisumu", 
      "latitude": "-0.1000", 
      "longitude": "34.7500", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kisumu", 
      "capital": "admin", 
      "population": "409928", 
      "population_proper": "409928"
    }, 
    {
      "city": "Nakuru", 
      "latitude": "-0.2833", 
      "longitude": "36.0667", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Nakuru", 
      "capital": "admin", 
      "population": "307990", 
      "population_proper": "307990"
    }, 
    {
      "city": "Eldoret", 
      "latitude": "0.5167", 
      "longitude": "35.2833", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Uasin Gishu", 
      "capital": "admin", 
      "population": "193830", 
      "population_proper": "193830"
    }, 
    {
      "city": "Machakos", 
      "latitude": "-1.5167", 
      "longitude": "37.2667", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Machakos", 
      "capital": "admin", 
      "population": "114109", 
      "population_proper": "114109"
    }, 
    {
      "city": "Kisii", 
      "latitude": "-0.6698", 
      "longitude": "34.7675", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kisii", 
      "capital": "admin", 
      "population": "112417", 
      "population_proper": "112417"
    }, 
    {
      "city": "Mumias", 
      "latitude": "0.3333", 
      "longitude": "34.4833", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kakamega", 
      "capital": "", 
      "population": "99987", 
      "population_proper": "99987"
    }, 
    {
      "city": "Thika", 
      "latitude": "-1.0396", 
      "longitude": "37.0900", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kiambu", 
      "capital": "", 
      "population": "99322", 
      "population_proper": "87821"
    }, 
    {
      "city": "Nyeri", 
      "latitude": "-0.4167", 
      "longitude": "36.9500", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Nyeri", 
      "capital": "admin", 
      "population": "98908", 
      "population_proper": "98908"
    }, 
    {
      "city": "Malindi", 
      "latitude": "-3.2100", 
      "longitude": "40.1000", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kilifi", 
      "capital": "", 
      "population": "94016", 
      "population_proper": "68304"
    }, 
    {
      "city": "Kakamega", 
      "latitude": "0.2833", 
      "longitude": "34.7500", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kakamega", 
      "capital": "admin", 
      "population": "91778", 
      "population_proper": "91778"
    }, 
    {
      "city": "Kendu Bay", 
      "latitude": "-0.3596", 
      "longitude": "34.6400", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Homa Bay", 
      "capital": "", 
      "population": "91248", 
      "population_proper": "91248"
    }, 
    {
      "city": "Lodwar", 
      "latitude": "3.1167", 
      "longitude": "35.6000", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Turkana", 
      "capital": "admin", 
      "population": "82970", 
      "population_proper": "82970"
    }, 
    {
      "city": "Athi River", 
      "latitude": "-1.4500", 
      "longitude": "36.9833", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Machakos", 
      "capital": "", 
      "population": "81302", 
      "population_proper": "81302"
    }, 
    {
      "city": "Kilifi", 
      "latitude": "-3.6333", 
      "longitude": "39.8500", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kilifi", 
      "capital": "", 
      "population": "80339", 
      "population_proper": "46118"
    }, 
    {
      "city": "Sotik", 
      "latitude": "-0.6796", 
      "longitude": "35.1200", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Bomet", 
      "capital": "", 
      "population": "71285", 
      "population_proper": "2600"
    }, 
    {
      "city": "Garissa", 
      "latitude": "-0.4569", 
      "longitude": "39.6583", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Garissa", 
      "capital": "admin", 
      "population": "65881", 
      "population_proper": "65881"
    }, 
    {
      "city": "Kitale", 
      "latitude": "1.0167", 
      "longitude": "35.0000", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Trans Nzoia", 
      "capital": "admin", 
      "population": "63245", 
      "population_proper": "63245"
    }, 
    {
      "city": "Bungoma", 
      "latitude": "0.5666", 
      "longitude": "34.5666", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Bungoma", 
      "capital": "admin", 
      "population": "55857", 
      "population_proper": "55857"
    }, 
    {
      "city": "Isiolo", 
      "latitude": "0.3500", 
      "longitude": "37.5833", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Isiolo", 
      "capital": "admin", 
      "population": "45989", 
      "population_proper": "45989"
    }, 
    {
      "city": "Wajir", 
      "latitude": "1.7500", 
      "longitude": "40.0667", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Wajir", 
      "capital": "admin", 
      "population": "45771", 
      "population_proper": "34709"
    }, 
    {
      "city": "Embu", 
      "latitude": "-0.5333", 
      "longitude": "37.4500", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Embu", 
      "capital": "admin", 
      "population": "41092", 
      "population_proper": "41092"
    }, 
    {
      "city": "Voi", 
      "latitude": "-3.3696", 
      "longitude": "38.5700", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Taita/Taveta", 
      "capital": "", 
      "population": "36487", 
      "population_proper": "19624"
    }, 
    {
      "city": "Homa Bay", 
      "latitude": "-0.5167", 
      "longitude": "34.4500", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Homa Bay", 
      "capital": "admin", 
      "population": "32174", 
      "population_proper": "32174"
    }, 
    {
      "city": "Nanyuki", 
      "latitude": "0.0167", 
      "longitude": "37.0667", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Laikipia", 
      "capital": "", 
      "population": "31577", 
      "population_proper": "31577"
    }, 
    {
      "city": "Busia", 
      "latitude": "0.4608", 
      "longitude": "34.1108", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Busia", 
      "capital": "admin", 
      "population": "30777", 
      "population_proper": "30777"
    }, 
    {
      "city": "Mandera", 
      "latitude": "3.9167", 
      "longitude": "41.8333", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Mandera", 
      "capital": "admin", 
      "population": "30433", 
      "population_proper": "30433"
    }, 
    {
      "city": "Kericho", 
      "latitude": "-0.3692", 
      "longitude": "35.2839", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kericho", 
      "capital": "admin", 
      "population": "30023", 
      "population_proper": "30023"
    }, 
    {
      "city": "Kitui", 
      "latitude": "-1.3667", 
      "longitude": "38.0167", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kitui", 
      "capital": "admin", 
      "population": "29062", 
      "population_proper": "29062"
    }, 
    {
      "city": "Maralal", 
      "latitude": "1.1000", 
      "longitude": "36.7000", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Samburu", 
      "capital": "admin", 
      "population": "20841", 
      "population_proper": "20841"
    }, 
    {
      "city": "Lamu", 
      "latitude": "-2.2686", 
      "longitude": "40.9003", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Lamu", 
      "capital": "admin", 
      "population": "18382", 
      "population_proper": "18382"
    }, 
    {
      "city": "Kapsabet", 
      "latitude": "0.2000", 
      "longitude": "35.1000", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Nandi", 
      "capital": "admin", 
      "population": "17918", 
      "population_proper": "17918"
    }, 
    {
      "city": "Marsabit", 
      "latitude": "2.3333", 
      "longitude": "37.9833", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Marsabit", 
      "capital": "admin", 
      "population": "17127", 
      "population_proper": "17127"
    }, 
    {
      "city": "Hola", 
      "latitude": "-1.5000", 
      "longitude": "40.0300", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Tana River", 
      "capital": "admin", 
      "population": "6931", 
      "population_proper": "6931"
    }, 
    {
      "city": "Kiambu", 
      "latitude": "-1.1714", 
      "longitude": "36.8356", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kiambu", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kabarnet", 
      "latitude": "0.4919", 
      "longitude": "35.7430", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Baringo", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Migori", 
      "latitude": "-1.0634", 
      "longitude": "34.4731", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Migori", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kerugoya", 
      "latitude": "-0.4989", 
      "longitude": "37.2803", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kirinyaga", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Iten", 
      "latitude": "0.6703", 
      "longitude": "35.5081", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Elgeyo/Marakwet", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Nyamira", 
      "latitude": "-0.5633", 
      "longitude": "34.9358", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Nyamira", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Murang’a", 
      "latitude": "-0.7210", 
      "longitude": "37.1526", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Murang’a", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Sotik Post", 
      "latitude": "-0.7813", 
      "longitude": "35.3416", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Bomet", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Siaya", 
      "latitude": "0.0607", 
      "longitude": "34.2881", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Siaya", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kapenguria", 
      "latitude": "1.2389", 
      "longitude": "35.1119", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "West Pokot", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Wote", 
      "latitude": "-1.7808", 
      "longitude": "37.6288", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Makueni", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mwatate", 
      "latitude": "-3.5050", 
      "longitude": "38.3772", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Taita/Taveta", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kajiado", 
      "latitude": "-1.8500", 
      "longitude": "36.7833", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kajiado", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ol Kalou", 
      "latitude": "-0.2643", 
      "longitude": "36.3788", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Nyandarua", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Narok", 
      "latitude": "-1.0833", 
      "longitude": "35.8667", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Narok", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kwale", 
      "latitude": "-4.1737", 
      "longitude": "39.4521", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Kwale", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Rumuruti", 
      "latitude": "0.2725", 
      "longitude": "36.5381", 
      "state": "Kenya", 
      "iso2": "KE", 
      "admin_name": "Laikipia", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }
  ]