module.exports.descriptors = [
    'Kudu',
    'Mianzi',
    'Mamba Village',
    'Mount Suswa',
    'Ngong Hills',
    'Mara',
    'Rapids Sagana',
    'Malta',
    'Olorgesaille',
    'Kiboko',
    'Watamu Village',
    'Leleshwa ',
    'Wilderbeast Eco',
    'Camp ya Kanzi',
    'Lake paradise',
    'Kembu',
    'Crater',
    'Kitich Forest',
    'Carnelleys',
    'Malewa Bush',
    'Mount Ololokwe',
    'Amboseli Bush',
    'Girrafe Centre',
    'Roberts-Paradise',
    'Ngare Ndare',
    'Lake Paradise',
    'Central Island',
    'Aberdare-Park',
    'Chyulu Hills',
    'Savannah',
    'Jacaranda Bush',
    'Mida Creek',
    'Rukenya Islands',
    'Talek Bush'

]

module.exports.places = [
    'Camp',
    'Village',
    'Canyon',
    'Luxury',
    'Group Camp',
    'Horse Camp',
    'Forest Hill',
    'Camp',
    'Dispersed Camp',
    'Resort',
    'River',
    'Campsite',
    'Special Campsite',
    'Farm',
    'Spring',
    'Crater Camp',
    'National Park',
    'Tented Camp',
    'Hunting Camp',
    'Cliffs',
    'Forest',
    'Camping-Site',
    'Camp',
    'Bush Camp',
    'Widlife Resort'
]

